#!/usr/bin/env perl

use strict;
use warnings;

use IO::Socket;

my @quotes = ();

my $temp;
open my $file, '<', 'quotes.txt';
while (<$file>) {
  if ($_ eq "\n") {
    push @quotes, $temp;
    $temp = '';
  } else {
    $temp .= $_;
  }
}

my $server = IO::Socket::INET->new(
  LocalPort => 17,
  Proto     => 'tcp',
  Reuse     => 1,
);

$server->listen;

while (my $client = $server->accept) {
  my $index = (time / 86400) % scalar @quotes;
  $client->print($quotes[$index]);
  $client->close;
}
