#!/usr/bin/env perl

use strict;
use warnings;

use IO::File;
use IO::Socket;

my @quotes = ();

my $temp;
my $file = IO::File->new('quotes.txt', 'r');
while (my $line = $file->getline) {
  if ($line eq "\n") {
    push @quotes, $temp;
    $temp = '';
  } else {
    $temp .= $line;
  }
}
$file->close;

my $server = IO::Socket::INET->new(
  LocalPort => 17,
  Proto     => 'tcp',
  Reuse     => 1,
);

$server->listen;

while (my $client = $server->accept) {
  my $index = (time / 86400) % scalar @quotes;
  $client->print($quotes[$index]);
  $client->close;
}
